### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by ravensoracle** [poke1024/tove2d#12] opened 2019-03-09 14:10 UTC
Could you add at least some docks? There are no autocompletions and it’s impossible to figure out what’s what, but it’s inconvenient and incomprehensible to look in the source code for what it means.

**Comment by poke1024** [comment] 2019-03-10 16:29
I should add docs indeed. Also the version you're using is probably the last release - the docs are out of sync currently and I need to build a new release that adds the "gpux" identifier (and a couple of bug fixes). Soon hopefully.

**Comment by poke1024** [comment] 2019-03-14 05:31
Since the gpux part of this issue is a duplicate of https://github.com/poke1024/tove2d/issues/1, I renamed it to focus on the adding of docs.

**Comment by poke1024** [comment] 2019-04-19 11:10
There's now an API documentation at https://poke1024.github.io/tove2d-api/.

I've also updated the general tutorials (now available at https://poke1024.github.io/tove2d/).

**Closed** 2019-04-21 11:12 UTC
Labels: enhancement
