### ISSUE TITLE
Render artifacts with gpux/shader

### ISSUE THREAD

**Issue by vitvakatu** [poke1024/tove2d#1] opened 2018-08-06 15:10 UTC
Hi! Just tried your library and found weird artifacts with all the examples
![screenshot_20180806_180901](https://user-images.githubusercontent.com/6566674/43724950-eeb015b0-99a3-11e8-8a42-2e0a4077abde.png)

I'm running Kubuntu with Intel integrated video card

**Comment by poke1024** [comment] 2018-08-08 17:18
Hm, this is going to be difficult to debug, esp. since I cannot reproduce this. Can you give an exact video card model?

Tove's shader renderer (i.e. the right one above) is a pretty brittle piece of GLSL programming with various texture lookups (including one binary search) depending on each other for reading out its data structures. If even one access is slightly off, the whole thing goes havoc. The turquoise color in the picture above are cases where this lookup failed. I've tested the thing with a couple of GPUs and one software renderer, but this above is some driver thing.

Here's some things you could try, which might help me understand what's going on:

* Run one example with `LIBGL_ALWAYS_SOFTWARE=1 love .`, i.e. forcing the software renderer instead of the hardware renderer.
* In your `lib/tove/init.lua` file (the one you downloaded), search for `rayOnX = dxy.x < dxy.y;` and change it to `rayOnX = true;`
* Likewise, you could try if changing `if string.find(device, "Parallels") ~= nil then` to `if true then` changes anything, this avoids using `mat3` which caused a problem with one driver.

**Comment by pdesaulniers** [comment] 2019-02-25 23:30
I can reproduce the issue, using the latest git version of the library on Arch Linux. The artifacts look identical:

![2019-02-25-18 29 26](https://user-images.githubusercontent.com/23723605/53376125-51302f00-392b-11e9-93b7-5d3f8c3ba2d1.png)

Regarding the three tests:

- Changing `if string.find(device, "Parallels") ~= nil then` doesn't seem to affect the issue at all

- Tweaking `rayOnX = dxy.x < dxy.y;` by itself looks like this

![2019-02-25-18 18 51](https://user-images.githubusercontent.com/23723605/53375642-d61a4900-3929-11e9-8e76-74b81c450b4c.png)

- Setting `LIBGL_ALWAYS_SOFTWARE=1` by itself looks like this:

![2019-02-25-18 25 28](https://user-images.githubusercontent.com/23723605/53376057-204ffa00-392b-11e9-8d7b-e8c09abbd8aa.png)

- When combined with the `rayOnX` tweak, we get this:

![2019-02-25-18 21 05](https://user-images.githubusercontent.com/23723605/53375757-209bc580-392a-11e9-9793-7c95b92676d6.png)

Running `lspci -vnn | grep VGA -A 12`  shows:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. 4th Gen Core Processor Integrated Graphics Controller [1043:157d]
	Flags: bus master, fast devsel, latency 0, IRQ 29
	Memory at ed400000 (64-bit, non-prefetchable) [size=4M]
	Memory at 80000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

Also, running the demo with my NVIDIA card shows an error:
```
Error

Cannot compile pixel shader code:
Line 382: error: ambiguous overloaded function reference "mix(ivec4, ivec4, bvec4)"


Traceback

[C]: in function 'newShader'
tove/init.lua:1324: in function 'newGeometryFillShader'
tove/init.lua:1750: in function 'newComputeFeedData'
tove/init.lua:1793: in function 'gen'
tove/init.lua:2284: in function 'shaders'
tove/init.lua:2470: in function 'f'
tove/init.lua:2502: in function '_create'
tove/init.lua:2217: in function 'draw'
assets/tovedemo.lua:109: in function 'draw'
main.lua:28: in function 'draw'
[C]: in function 'xpcall'

```

**Comment by poke1024** [comment] 2019-02-26 19:35
@pdesaulniers The NVIdia error is a correct error due to a GLSL call I messed up - should be fixed in top of tree (I'm planning to make an official release in the next weeks where this is included).

The artefacts problem is difficult. I can now also reproduce this with one machine here.  I need to think about how to add debugging code to tackle this.

**Comment by pdesaulniers** [comment] 2019-03-17 22:21
Seems like it's working now! I'm not getting any weird artifacts using either my Intel or NVIDIA card:

![2019-03-17-18:19:36](https://user-images.githubusercontent.com/23723605/54498761-5d335f00-48e1-11e9-97ef-f89363542329.png)

**Comment by poke1024** [comment] 2019-03-17 22:50
I had hoped for this. With the last commits from today, I can no longer reproduce issues. I tested with NVidia on Windows and Linux, as well with Intel hardware drivers on macOS.

**Comment by poke1024** [comment] 2019-03-28 06:28
I tested again on all devices I own. Seems it's working everywhere now.

**Closed by poke1024** 2019-03-28 06:28 UTC
Labels: bug
